security:
    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login: ~
#                login_path:  login
#                check_path:  login_check

    access_control:
        - { path: ^/shop/list, roles: ROLE_USER }
        - { path: ^/shop/add, roles: ROLE_ADMIN }
        # Descomenta la siguiente línea para proteger también
        # la propia URL /admin
        # - { path: ^/admin$, roles: ROLE_ADMIN }

    providers:
        in_memory:
            memory:
                users:
                    andres:  { password: andpass, roles: 'ROLE_USER' }
                    admin: { password: kitten, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

#security:
#    providers:
#        in_memory:
#            memory: ~
#
#    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        default:
#            anonymous: ~