parameters:
#    coffee_api.example.class: Coffee\ApiBundle\Example

services:
#    coffee_api.example:
#        class: %coffee_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
